/*
 * This file was automatically generated by EvoSuite
 * Mon Feb 12 23:27:09 GMT 2024
 */

package org.jsoup.examples;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteURL;
import org.evosuite.runtime.testdata.NetworkHandling;
import org.jsoup.examples.HtmlToPlainText;
import org.jsoup.nodes.Attributes;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.nodes.FormElement;
import org.jsoup.parser.ParseSettings;
import org.jsoup.parser.Parser;
import org.jsoup.parser.Tag;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HtmlToPlainText_ESTest extends HtmlToPlainText_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.w3.org/XML/1998/namespace");
      String[] stringArray0 = new String[1];
      stringArray0[0] = "http://www.w3.org/XML/1998/namespace";
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "http://www.w3.org/2000/svghttp://www.w3.org/1999/xhtml\nhttp://www.w3.org/1999/xhtml");
      HtmlToPlainText.main(stringArray0);
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HtmlToPlainText htmlToPlainText0 = new HtmlToPlainText();
      Parser parser0 = Parser.xmlParser();
      Document document0 = parser0.parseInput("org.jsoup.select.Evaluator$ContainsData", "http://www.w3.org/2000/svg");
      document0.append("http://www.w3.org/1999/xhtml");
      document0.appendText("http://www.w3.org/1999/xhtml");
      String string0 = htmlToPlainText0.getPlainText(document0);
      assertEquals("org.jsoup.select.Evaluator$ContainsDatahttp://www.w3.org/1999/xhtml\nhttp://www.w3.org/1999/xhtml", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      HtmlToPlainText htmlToPlainText0 = new HtmlToPlainText();
      Parser parser0 = Parser.xmlParser();
      Document document0 = parser0.parseInput("  ", "]rWO>F-?7LjN=H6");
      htmlToPlainText0.getPlainText(document0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      HtmlToPlainText htmlToPlainText0 = new HtmlToPlainText();
      Element element0 = new Element("br", "br");
      String string0 = htmlToPlainText0.getPlainText(element0);
      assertEquals("\n", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      HtmlToPlainText htmlToPlainText0 = new HtmlToPlainText();
      ParseSettings parseSettings0 = ParseSettings.preserveCase;
      Tag tag0 = Tag.valueOf("li", parseSettings0);
      Attributes attributes0 = new Attributes();
      FormElement formElement0 = new FormElement(tag0, (String) null, attributes0);
      String string0 = htmlToPlainText0.getPlainText(formElement0);
      assertEquals("\n * ", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      String[] stringArray0 = new String[2];
      // Undeclared exception!
      try { 
        HtmlToPlainText.main(stringArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The 'url' parameter must not be empty.
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      String[] stringArray0 = new String[5];
      // Undeclared exception!
      try { 
        HtmlToPlainText.main(stringArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // usage: java -cp jsoup.jar org.jsoup.examples.HtmlToPlainText url [selector]
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }
}
