/*
 * This file was automatically generated by EvoSuite
 * Mon Feb 12 23:22:59 GMT 2024
 */

package org.jsoup;

import org.junit.Test;
import static org.junit.Assert.*;
import java.io.IOException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockIOException;
import org.jsoup.UncheckedIOException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UncheckedIOException_ESTest extends UncheckedIOException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UncheckedIOException uncheckedIOException0 = new UncheckedIOException("R]c&j+3niVX4t");
      IOException iOException0 = uncheckedIOException0.ioException();
      assertNotNull(iOException0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UncheckedIOException uncheckedIOException0 = new UncheckedIOException("R]c&j+3niVX4t");
      MockIOException mockIOException0 = new MockIOException(uncheckedIOException0);
      UncheckedIOException uncheckedIOException1 = new UncheckedIOException(mockIOException0);
      assertEquals("org.evosuite.runtime.mock.java.lang.MockThrowable: org.jsoup.UncheckedIOException: org.evosuite.runtime.mock.java.lang.MockThrowable: R]c&j+3niVX4t", uncheckedIOException1.getMessage());
  }
}
